### ISSUE TITLE
Make target "grammar" not working

### ISSUE THREAD

**Issue by kivismik** [erikinkinen/ankka-compiler#1]
[hadoop@hosti ankka-compiler]$ make
make grammar
make[1]: Entering directory `/home/hadoop/ankka/ankka-compiler'
bison -d grammar.y
grammar.y:19.24-36: error: syntax error, unexpected {...}
make[1]: *** [grammar] Error 1
make[1]: Leaving directory `/home/hadoop/ankka/ankka-compiler'
make: *** [all] Error 2
[hadoop@hosti ankka-compiler]$

**Comment by kivismik** [comment]
We are a Fortune 500 Company in Finland looking forward to move our ERP in-house solution to be ankka based.

**Comment by erikinkinen** [comment]
This project is not ready for real usage yet and I don't have time to develop it anymore. Still, thank you for your interest. :-)
